<a href="https://colab.research.google.com/github/ibnMuxiddin/Data-since/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
list = [5, 10, 15, 20, 25]
arr = np.array(list)
arr

array([ 5, 10, 15, 20, 25])

In [6]:
arr1 = np.arange(0, 26, 5)
arr1

array([ 0,  5, 10, 15, 20, 25])

In [10]:
arr2 = np.arange(18).reshape(3,6)
arr2
arr2.ndim

2

In [9]:
arr3 = np.arange(19)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [11]:
arr4 = np.array([[1, 2, 3], [4, 5, 6]])
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr5 = np.arange(1,7).reshape(2,3)
arr5

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr6 = np.arange(1, 25).reshape(2,3,4)
print(arr6)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [22]:
arr7 = np.zeros((3,4))
arr7

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
def arr_zeros(a, b):
  arr = np.zeros((a,b))
  return arr
arr_zeros(3,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
arr_10 = np.array([10, 20, 30, 40, 50])
arr_10[1:4]

array([20, 30, 40])

In [28]:
arr_1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr_1[1, 1]

np.int64(5)

In [30]:
arr_1[1]

array([4, 5, 6])

In [33]:
i = 0
new_list = []
for _ in arr_1:
  new_list.append(arr_1[i,2])
  i += 1
new_arr = np.array(new_list)
new_arr

array([3, 6, 9])

In [36]:
arr_1[2, :]

array([7, 8, 9])

In [41]:
arr_1[0:2, 1:2]

array([[2],
       [5]])

In [46]:
a = arr_1[:, 2:]
a.ndim

2

In [50]:
np.arange(0,16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])