<a href="https://colab.research.google.com/github/ibnMuxiddin/Data-since/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy kutubxonasini chaqirish

In [1]:
import numpy as np


Massiv elementlariga murojaat qilish

In [52]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


Bitta elementga murojaat qilish

In [54]:
print(arr[1,1])

50


Ikkinchi qatorni olish


In [55]:
print(arr[1])

[40 50 60]


uchunchi ustunni olish

In [56]:
print(arr[:, 2])

[30 60 90]


Boolen indexlash

In [57]:
arr1 = np.arange(0, 56, 5)
print(arr1)

[ 0  5 10 15 20 25 30 35 40 45 50 55]


In [59]:
print(arr1[arr1>10])

[15 20 25 30 35 40 45 50 55]


Boolen indexlashda AND operatori

In [60]:
arr2 = np.array([8, 15, 3, 22, 10, 18, 5])
print(arr2)

[ 8 15  3 22 10 18  5]


In [63]:
print(arr2[(arr2 > 10) & (arr2 < 20)])

[15 18]


In [64]:
arr3 = np.array([
    [5, 12, 7],
    [20, 3, 15],
    [8, 25, 10]
])
print(arr3)

[[ 5 12  7]
 [20  3 15]
 [ 8 25 10]]


In [65]:
print(arr3[arr3 > 10])

[12 20 15 25]
